site_name: Algorithm

theme:
  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  name: null
  custom_dir: material
  palette:
    scheme: rubble
  font: false
  language: en
  features:
    # - navigation.instant
    - navigation.tabs
    - tabs.changeicon
    - toc.autohide
    - colors
  icons:
    _algorithm: custom/light-bulb
    _exercises: custom/key3
  colors:
    default: /#393333
    home: /#666666
    _algorithm: /#088e11
    _exercises: /#088e11

  icon:
    logo: custom/light-bulb
  favicon: assets/t.svg

extra_css:
  - css/general.css
  - css/fonts.css
  - css/code-admonition.css
  - css/katex.css
  - css/tables.css
  - css/extra/admonitions.css
  - css/extra/code-blocks.css
  - css/gadgets/book.css
  - 'https://cdn.jsdelivr.net/npm/katex@0.13.0/dist/katex.min.css'

extra_javascript:
  - 'https://cdn.jsdelivr.net/npm/katex@0.13.0/dist/katex.min.js'
  - 'https://cdn.jsdelivr.net/npm/katex@0.13.0/dist/contrib/auto-render.min.js'
  - 'js/mkmain.js'
  - 'js/katex.js'

markdown_extensions:
  - abbr
  - attr_list
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      use_pygments: true
      linenums_style: table
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - footnotes
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: 🧐
      toc_depth: 6 # Define the range of levels to be included in the table of contents
  - meta

plugins:
  - search

nav:
  - home: index.md
  - algorithm🤖:
      - Preface: _algorithm/index.md
      - Data Structures:
        - heap: _algorithm/_ds/heap.md
        - union-find set: _algorithm/_ds/ufset.md
      - Sort:
        - merge sort: _algorithm/_sort/mergesort.md
      - Advanced Techniques:
        - 1. dynamic programming: _algorithm/_advt/1.md
        - 2. greedy algorithm: _algorithm/_advt/2.md
      - Graph Algorithms:
        - _outline_: _algorithm/_graph/basis.md
        - 1. basis: _algorithm/_graph/basis.md
        - 2. minium spanning trees: _algorithm/_graph/mst.md
        - 3. single-source shortest paths: _algorithm/_graph/ss_shortest.md
        - 4. all-pairs shortest paths: _algorithm/_graph/ss_allpairs.md
  - problems🏁:
      - Preface: _problems/index.md
      - HashMap: _problems/_hashmap/hashmap.md
      - Binary Tree: _problems/_binary_tree/binary_tree.md
      - DFS / BFS: _problems/_search/search.md
      - DP:
          - linear: _problems/_dp/linear.md
          - pack: _problems/_dp/pack.md
      - Others: _problems/_others/others.md
      - List:
          - 1. two sum: _problems/_leetcode/1.md
          - 2. add two numbers: _problems/_leetcode/2.md
          - 10. regular exp matching: _problems/_leetcode/10_regular_exp_matching.md
          - 20. valid parentheses: _problems/_leetcode/20.md
          - 23. merge K sorted lists: _problems/_leetcode/23_merge_k_sorted_lists.md
          - 31. next permutation: _problems/_leetcode/31.md
          - 44. wildcard matching: _problems/_leetcode/44_wildcard_matching.md
          - 46. permutations: _problems/_leetcode/46.md
          - 47. permutations ii: _problems/_leetcode/47.md
          - 53. maximum subarray: _problems/_leetcode/53_maximum_subarray.md
          - 72. edit distance: _problems/_leetcode/72_edit_distance.md
          - 112. path sum: _problems/_leetcode/112.md
          - 113. path sum ii: _problems/_leetcode/113.md
          - 120. triangle: _problems/_leetcode/120_triangle.md
          - 121. best time to sell stock: _problems/_leetcode/121_best_time_to_sell_stock.md
          - 122. best time to sell stock ii: _problems/_leetcode/122_best_time_to_sell_stock_ii.md
          - 123. best time to sell stock iii: _problems/_leetcode/123_best_time_to_sell_stock_iii.md
          - 128. longest consecutive sequence: _problems/_leetcode/128_longest_consecutive_sequence.md
          - 130. surround regions: _problems/_leetcode/130_surrounded_regions.md
          - 152. maximum product subarray: _problems/_leetcode/152_maximum_product_subarray.md
          - 188. best time to sell stock iv: _problems/_leetcode/188_best_time_to_sell_stock_iv.md
          - 200. number of islands: _problems/_leetcode/200_number_of_islands.md
          - 206. reverse linked list: _problems/_leetcode/206.md
          - 207. course schedule: _problems/_leetcode/207.md
          - 210. course schedule ii: _problems/_leetcode/210.md
          - 263. ugly number: _problems/_leetcode/263.md
          - 300. longest increasing subsequence: _problems/_leetcode/300_longest_increasing_subsequence.md
          - 309. best time to sell stock with cooldown: _problems/_leetcode/309_best_time_to_buy_and_sell_stock_with_cooldown.md
          - 310. minumum height trees: _problems/_leetcode/310.md
          - 313. super ugly number: _problems/_leetcode/313.md
          - 322. coin change: _problems/_leetcode/322_coin_change.md
          - 413. arithmetic slices: _problems/_leetcode/413.md
          - 416. partition equal subset sum: _problems/_leetcode/416_partition_equal_subset_sum.md
          - 437. path sum iii: _problems/_leetcode/437.md
          - 474. ones and zeroes: _problems/_leetcode/474_ones_and_zeroes.md
          - 494. target sum: _problems/_leetcode/494_target_sum.md
          - 518. coin change 2: _problems/_leetcode/518_coin_change_2.md
          - 560. subarrray sum equals k: _problems/_leetcode/560.md
          - 671. second minimum node in a binary tree: _problems/_leetcode/671.md
          - 714. best time to sell stock with transaction fee: _problems/_leetcode/714_best_time_to_buy_and_sell_stock_with_transaction_fee.md
          - 803. bricks failing when hit: _problems/_leetcode/803_bricks_failing_when_hit.md
          - 979. distribute coins in binary tree: _problems/_leetcode/979.md
          - 996. number of squareful arrays: _problems/_leetcode/996.md