site_name: Algorithm

theme:
  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  name: null
  custom_dir: material
  palette:
    scheme: rubble
  font: false
  language: en
  features:
    # - navigation.instant
    - navigation.tabs
    - tabs.changeicon
    - toc.autohide
    - colors
  icons:
    _algorithm: custom/light-bulb
    _exercises: custom/key3
  colors:
    default: /#393333
    home: /#666666
    _algorithm: /#088e11
    _exercises: /#088e11

  icon:
    logo: custom/light-bulb
  favicon: assets/t.svg

extra_css:
  - css/general.css
  - css/fonts.css
  - css/code-admonition.css
  - css/katex.css
  - css/tables.css
  - css/extra/admonitions.css
  - css/extra/code-blocks.css
  - css/gadgets/book.css
  - 'https://cdn.jsdelivr.net/npm/katex@0.13.0/dist/katex.min.css'

extra_javascript:
  - 'https://cdn.jsdelivr.net/npm/katex@0.13.0/dist/katex.min.js'
  - 'https://cdn.jsdelivr.net/npm/katex@0.13.0/dist/contrib/auto-render.min.js'
  - 'js/mkmain.js'
  - 'js/katex.js'

markdown_extensions:
  - abbr
  - attr_list
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      use_pygments: true
      linenums_style: table
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - footnotes
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: 🧐
      toc_depth: 6 # Define the range of levels to be included in the table of contents
  - meta

plugins:
  - search

nav:
  - home: index.md
  - algorithm🤖:
      - Preface: _algorithm/index.md
      - Advanced Techniques:
        - 1. dynamic programming: _algorithm/_advt/1.md
        - 2. greedy algorithm: _algorithm/_advt/2.md
      - Graph Algorithms:
        - 1. a: _algorithm/_graph/1.md
  - problems🏁:
      - Preface: _problems/index.md
      - DP:
          - pack: _problems/_dp/pack.md
      - List:
          - 10. regular exp matching: _problems/_leetcode/10_regular_exp_matching.md
          - 120. triangle: _problems/_leetcode/120_triangle.md
          - 322. coin change: _problems/_leetcode/322_coin_change.md
          - 416. partition equal subset sum: _problems/_leetcode/416_partition_equal_subset_sum.md
          - 474. ones and zeroes: _problems/_leetcode/474_ones_and_zeroes.md
          - 494. target sum: _problems/_leetcode/494_target_sum.md
          - 518. coin change 2: _problems/_leetcode/518_coin_change_2.md