site_name: Algorithm

theme:
  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  name: null
  custom_dir: material
  palette:
    scheme: rubble
  font: false
  language: en
  features:
    # - navigation.instant
    - navigation.tabs
    - tabs.changeicon
    - toc.autohide
    - colors
  icons:
    _algorithm: custom/light-bulb
    _exercises: custom/key3
  colors:
    default: /#393333
    home: /#666666
    _algorithm: /#088e11
    _exercises: /#088e11

  icon:
    logo: custom/light-bulb
  favicon: assets/t.svg

extra_css:
  - css/general.css
  - css/fonts.css
  - css/code-admonition.css
  - css/katex.css
  - css/tables.css
  - css/extra/admonitions.css
  - css/extra/code-blocks.css
  - css/gadgets/book.css
  - 'https://cdn.jsdelivr.net/npm/katex@0.13.0/dist/katex.min.css'

extra_javascript:
  - 'https://cdn.jsdelivr.net/npm/katex@0.13.0/dist/katex.min.js'
  - 'https://cdn.jsdelivr.net/npm/katex@0.13.0/dist/contrib/auto-render.min.js'
  - 'js/mkmain.js'
  - 'js/katex.js'

markdown_extensions:
  - abbr
  - attr_list
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      use_pygments: true
      linenums_style: table
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - footnotes
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: 🧐
      toc_depth: 6 # Define the range of levels to be included in the table of contents
  - meta

plugins:
  - search

variables:
  - leetcode_problems_path: &leet _problems/_leetcode


nav:
  - home: index.md
  - algorithm🤖:
      - Preface: _algorithm/index.md
      - Data Structures:
        - heap: _algorithm/_ds/heap.md
        - union-find set: _algorithm/_ds/ufset.md
      - Sort:
        - merge sort: _algorithm/_sort/mergesort.md
      - Binary Search: _algorithm/_binary_search/binary_search.md
      - Advanced Techniques:
        - 1. dynamic programming: _algorithm/_advt/1.md
        - 2. greedy algorithm: _algorithm/_advt/2.md
      - Graph Algorithms:
        - _outline_: _algorithm/_graph/basis.md
        - 1. basis: _algorithm/_graph/basis.md
        - 2. minium spanning trees: _algorithm/_graph/mst.md
        - 3. single-source shortest paths: _algorithm/_graph/ss_shortest.md
        - 4. all-pairs shortest paths: _algorithm/_graph/ss_allpairs.md
      - String Algorithms:
        - 1. trie: _algorithm/_string/trie.md
  - problems🏁:
      - Preface: _problems/index.md
      - HashMap: _problems/_hashmap/hashmap.md
      - Binary Tree: _problems/_binary_tree/binary_tree.md
      - DFS / BFS: _problems/_search/search.md
      - DP:
          - linear: _problems/_dp/linear.md
          - interval: _problems/_dp/interval.md
          - pack: _problems/_dp/pack.md
      - Simulation: _problems/_simul/simul.md
      - Others: _problems/_others/others.md
      - List:
          - 1. two sum: _problems/_leetcode/1.md
          - 2. add two numbers: _problems/_leetcode/2.md
          - 10. regular exp matching: _problems/_leetcode/10_regular_exp_matching.md
          - 15. three sum: !!python/object/apply:os.path.join [*leet, 15.md]
          - 16. three sum closet: !!python/object/apply:os.path.join [*leet, 16.md]
          - 20. valid parentheses: _problems/_leetcode/20.md
          - 22. generate parentheses: !!python/object/apply:os.path.join [*leet, 22.md]
          - 23. merge K sorted lists: _problems/_leetcode/23_merge_k_sorted_lists.md
          - 27. remove element: !!python/object/apply:os.path.join [*leet, 27.md]
          - 31. next permutation: _problems/_leetcode/31.md
          - 34. find first and last position of element in sorted array: !!python/object/apply:os.path.join [*leet, 34.md]
          - 39. combination sum: !!python/object/apply:os.path.join [*leet, 39.md]
          - 40. combination sum ii: !!python/object/apply:os.path.join [*leet, 40.md]
          - 42. trapping rain water: !!python/object/apply:os.path.join [*leet, 42.md]
          - 44. wildcard matching: _problems/_leetcode/44_wildcard_matching.md
          - 45. jump game ii: !!python/object/apply:os.path.join [*leet, 45.md]
          - 46. permutations: _problems/_leetcode/46.md
          - 47. permutations ii: _problems/_leetcode/47.md
          - 53. maximum subarray: _problems/_leetcode/53_maximum_subarray.md
          - 55. jump game: !!python/object/apply:os.path.join [*leet, 55.md]
          - 57. insert interval: !!python/object/apply:os.path.join [*leet, 57.md]
          - 60. permutation sequence: _problems/_leetcode/60.md
          - 71. simplify path: !!python/object/apply:os.path.join [*leet, 71.md]
          - 72. edit distance: _problems/_leetcode/72_edit_distance.md
          - 79. word search: !!python/object/apply:os.path.join [*leet, 79.md]
          - 84. largest rectangle in histogram: !!python/object/apply:os.path.join [*leet, 84.md]
          - 85. maximal rectangle: !!python/object/apply:os.path.join [*leet, 85.md]
          - 86. partition list: !!python/object/apply:os.path.join [*leet, 86.md]
          - 91. decode ways: !!python/object/apply:os.path.join [*leet, 91.md]
          - 101. symmetric tree: !!python/object/apply:os.path.join [*leet, 101.md]
          - 102. binary tree level order traversal: !!python/object/apply:os.path.join [*leet, 102.md]
          - 103. binary tree zigzag level order traversal: !!python/object/apply:os.path.join [*leet, 103.md]
          - 105. construct binary tree from preorder and inorder traversal: !!python/object/apply:os.path.join [*leet, 105.md]
          - 106. construct binary tree from inorder and postorder traversal: !!python/object/apply:os.path.join [*leet, 106.md]
          - 112. path sum: _problems/_leetcode/112.md
          - 113. path sum ii: _problems/_leetcode/113.md
          - 120. triangle: _problems/_leetcode/120_triangle.md
          - 121. best time to sell stock: _problems/_leetcode/121_best_time_to_sell_stock.md
          - 122. best time to sell stock ii: _problems/_leetcode/122_best_time_to_sell_stock_ii.md
          - 123. best time to sell stock iii: _problems/_leetcode/123_best_time_to_sell_stock_iii.md
          - 124. binary tree maximum path sum: !!python/object/apply:os.path.join [*leet, 124.md]
          - 128. longest consecutive sequence: _problems/_leetcode/128_longest_consecutive_sequence.md
          - 130. surround regions: _problems/_leetcode/130_surrounded_regions.md
          - 134. gas station: !!python/object/apply:os.path.join [*leet, 134.md]
          - 138. copy list with random pointer: !!python/object/apply:os.path.join [*leet, 138.md]
          - 139. word break: !!python/object/apply:os.path.join [*leet, 139.md]
          - 140. word break ii: !!python/object/apply:os.path.join [*leet, 140.md]
          - 143. reorder list: !!python/object/apply:os.path.join [*leet, 143.md]
          - 152. maximum product subarray: _problems/_leetcode/152_maximum_product_subarray.md
          - 155. min stack: !!python/object/apply:os.path.join [*leet, 155.md]
          - 162. find peak element: !!python/object/apply:os.path.join [*leet, 162.md]
          - 165. compare version numbers: !!python/object/apply:os.path.join [*leet, 165.md]
          - 166. fraction to recurring decimal: !!python/object/apply:os.path.join [*leet, 166.md]
          - 167. two sum ii: !!python/object/apply:os.path.join [*leet, 167.md]
          - 179. largest number: !!python/object/apply:os.path.join [*leet, 179.md]
          - 188. best time to sell stock iv: _problems/_leetcode/188_best_time_to_sell_stock_iv.md
          - 198. house robbery: !!python/object/apply:os.path.join [*leet, 198.md]
          - 199. binary tree right side view: !!python/object/apply:os.path.join [*leet, 199.md]
          - 200. number of islands: _problems/_leetcode/200_number_of_islands.md
          - 206. reverse linked list: _problems/_leetcode/206.md
          - 207. course schedule: _problems/_leetcode/207.md
          - 208. implement trie prefix tree: !!python/object/apply:os.path.join [*leet, 208.md]
          - 209. mininum size subarray sum: !!python/object/apply:os.path.join [*leet, 209.md]
          - 210. course schedule ii: _problems/_leetcode/210.md
          - 212. word search ii: !!python/object/apply:os.path.join [*leet, 212.md]
          - 213. house robbery ii: !!python/object/apply:os.path.join [*leet, 213.md]
          - 239. sliding window maximum: !!python/object/apply:os.path.join [*leet, 239.md]
          - 263. ugly number: _problems/_leetcode/263.md
          - 300. longest increasing subsequence: _problems/_leetcode/300_longest_increasing_subsequence.md
          - 309. best time to sell stock with cooldown: _problems/_leetcode/309_best_time_to_buy_and_sell_stock_with_cooldown.md
          - 310. minumum height trees: _problems/_leetcode/310.md
          - 312. burst ballons: !!python/object/apply:os.path.join [*leet, 312.md]
          - 313. super ugly number: _problems/_leetcode/313.md
          - 322. coin change: _problems/_leetcode/322_coin_change.md
          - 337. house robbery iii: !!python/object/apply:os.path.join [*leet, 337.md]
          - 384. shuffle an array: !!python/object/apply:os.path.join [*leet, 384.md]
          - 386. lexicographical numbers: !!python/object/apply:os.path.join [*leet, 386.md]
          - 394. decode string: !!python/object/apply:os.path.join [*leet, 394.md]
          - 410. split array largest sum: !!python/object/apply:os.path.join [*leet, 410.md]
          - 413. arithmetic slices: _problems/_leetcode/413.md
          - 416. partition equal subset sum: _problems/_leetcode/416_partition_equal_subset_sum.md
          - 437. path sum iii: _problems/_leetcode/437.md
          - 440. kth smallest in lexicographical order: !!python/object/apply:os.path.join [*leet, 440.md]
          - 446. arithmetic slices ii subsequence: _problems/_leetcode/446.md
          - 447. number of boomerangs: !!python/object/apply:os.path.join [*leet, 447.md]
          - 474. ones and zeroes: _problems/_leetcode/474_ones_and_zeroes.md
          - 494. target sum: _problems/_leetcode/494_target_sum.md
          - 498. diagonal traverse: !!python/object/apply:os.path.join [*leet, 498.md]
          - 518. coin change 2: _problems/_leetcode/518_coin_change_2.md
          - 526. beautiful arrangement: !!python/object/apply:os.path.join [*leet, 526.md]
          - 543. diameter of binary tree: !!python/object/apply:os.path.join [*leet, 543.md]
          - 556. next greater element iii: !!python/object/apply:os.path.join [*leet, 556.md]
          - 560. subarrray sum equals k: _problems/_leetcode/560.md
          - 576. out of boundary paths: !!python/object/apply:os.path.join [*leet, 576.md]
          - 600. non-negative integers without consective 1s: !!python/object/apply:os.path.join [*leet, 600.md]
          - 621. task scheduler: !!python/object/apply:os.path.join [*leet, 621.md]
          - 633. sum of square numbers: !!python/object/apply:os.path.join [*leet, 633.md]
          - 664. strange printer: !!python/object/apply:os.path.join [*leet, 664.md]
          - 670. maximum swap: !!python/object/apply:os.path.join [*leet, 670.md]
          - 671. second minimum node in a binary tree: _problems/_leetcode/671.md
          - 714. best time to sell stock with transaction fee: _problems/_leetcode/714_best_time_to_buy_and_sell_stock_with_transaction_fee.md
          - 803. bricks failing when hit: _problems/_leetcode/803_bricks_failing_when_hit.md
          - 852. peak index in a mountain array: !!python/object/apply:os.path.join [*leet, 852.md]
          - 875. koko eating bananas: !!python/object/apply:os.path.join [*leet, 875.md]
          - 876. middle of the linked list: !!python/object/apply:os.path.join [*leet, 876.md]
          - 887. super egg drop: !!python/object/apply:os.path.join [*leet, 887.md]
          - 979. distribute coins in binary tree: _problems/_leetcode/979.md
          - 987. vertical order traversal of a binary tree: !!python/object/apply:os.path.join [*leet, 987.md]
          - 996. number of squareful arrays: _problems/_leetcode/996.md
          - 1027. longest arithmetic subsequence: _problems/_leetcode/1027.md
          - 1894. find the student that will replace the chalk: !!python/object/apply:os.path.join [*leet, 1894.md]