site_name: Algorithm

theme:
  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  name: null
  custom_dir: material
  palette:
    scheme: rubble
  font: false
  language: en
  features:
    # - navigation.instant
    - navigation.tabs
    - tabs.changeicon
    - toc.autohide
    - colors
  icons:
    _algorithm: custom/light-bulb
    _exercises: custom/key3
  colors:
    default: /#393333
    home: /#666666
    _algorithm: /#088e11
    _exercises: /#088e11

  icon:
    logo: custom/light-bulb
  favicon: assets/t.svg

extra_css:
  - css/general.css
  - css/fonts.css
  - css/code-admonition.css
  - css/katex.css
  - css/tables.css
  - css/extra/admonitions.css
  - css/extra/code-blocks.css
  - css/gadgets/book.css
  - 'https://cdn.jsdelivr.net/npm/katex@0.13.0/dist/katex.min.css'

extra_javascript:
  - 'https://cdn.jsdelivr.net/npm/katex@0.13.0/dist/katex.min.js'
  - 'https://cdn.jsdelivr.net/npm/katex@0.13.0/dist/contrib/auto-render.min.js'
  - 'js/mkmain.js'
  - 'js/katex.js'

markdown_extensions:
  - abbr
  - attr_list
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      use_pygments: true
      linenums_style: table
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - footnotes
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: 🧐
      toc_depth: 6 # Define the range of levels to be included in the table of contents
  - meta

plugins:
  - search

nav:
  - home: index.md
  - algorithm🤖:
      - Preface: _algorithm/index.md
  - exercises🏁:
      - Preface: _exercises/index.md